#!/bin/bash

## Template directory location
BASE_TMPL_DIR="${HOME}/Templates/tex-templates"

## Default values
TITLE="Some Title"
AUTHOR="Some Author"
PROJECT_DIRECTORY="latex"
TEMPLATE_KIND="article"

## other variables
SCRIPT_NAME=$0

usage () {
    echo -e "\
usage: ${SCRIPT_NAME} [options ...] [project directory]

 Generates a fresh tex project in [project directory], or directory name 
 \"${PROJECT_DIRECTORY}\" in the current directory if none is supplied.

 Template files are stored at \"${TMPL_DIR}\".

   -t, --title TITLE    document title. Defaults to \"${TITLE}\"
   -a, --author AUTHOR  document author. Defaults to \"${AUTHOR}\"
   -h, --help           print this message
   -s, --style          style of template to use. Defaults to \"${TEMPLATE_KIND}\"

By Anders Dalskov. No warrenty and so on ..."
}

err () {
    >&2 echo $1
    usage
    exit 1
}

if ! [ -d "${BASE_TMPL_DIR}" ]; then
    err "no such directory: ${BASE_TMPL_DIR}"
fi

while [[ $# -gt 0 ]]; do
    k="$1"

    case $k in
	-t|--title)
	    TITLE=$2
	    shift
	    shift
	    ;;
	-a|--author)
	    AUTHOR=$2
	    shift
	    shift
	    ;;
	-h|--help)
	    usage
	    exit 0
	    ;;
        -s|--style)
            TEMPLATE_KIND=$2
            shift
            shift
            ;;
	*)
	    PROJECT_DIRECTORY=$1
	    shift
	    ;;
    esac
done

TMPL_DIR="${BASE_TMPL_DIR}/${TEMPLATE_KIND}"

if ! [ -e "${TMPL_DIR}/.flag" ]; then
    err "unknwon template: ${TEMPLATE_KIND}"
fi

if [ -d "${PROJECT_DIR}" ]; then
    err "directory ${PROJECT_DIR} already exists"
fi

echo "creating directry ..."
mkdir -p "${PROJECT_DIRECTORY}/sections"

echo "copying files ..."
cp -r "${TMPL_DIR}/*.tex" "${PROJECT_DIRECTORY}"

echo "setting default values ..."
sed -i "s/\\\\title{}/\\\\title{${TITLE}}/g" "${PROJECT_DIRECTORY}/main.tex"
sed -i "s/\\\\author{}/\\\\author{${AUTHOR}}/g" "${PROJECT_DIRECTORY}/main.tex"
